/* eslint-disable no-restricted-exports */
import React from 'react'

import { AdminBar } from '../../components/AdminBar'
import { Header } from './_components/Header'
import './app.scss'
import { draftMode } from 'next/headers'

export const metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
}

export default async function RootLayout(props: { children: React.ReactNode }) {
  const { isEnabled } = await draftMode()
  const { children } = props

  return (
    <html lang="en">
      <body>
        <AdminBar
          adminBarProps={{
            preview: isEnabled,
          }}
        />
        <Header />
        {children}
      </body>
    </html>
  )
}
